name: Build AgeraPvP Helper 1.8.9

on:
  push:
    branches:
      - build-agerapvp-1.8.9
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: agerapvp189
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '8'

      - name: Setup Gradle 2.14.1
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '2.14.1'

      - name: Build
        run: gradle clean build --stacktrace

      - name: Upload mod jar
        uses: actions/upload-artifact@v4
        with:
          name: AgeraPvPHelper-1.8.9-Forge-1.1.1
          path: agerapvp189/build/libs/*.jar
